### ISSUE TITLE
Deploy test reports to Bitrise.io (exit code: 1)       

### ISSUE THREAD

**Issue by AsifDev21** [bitrise-io/steps-deploy-to-bitrise-io#44] opened 2017-08-31 10:37 UTC
+------------------------------------------------------------------------------+

| (10) Deploy test reports to Bitrise.io                                       |
+------------------------------------------------------------------------------+
| id: deploy-to-bitrise-io                                                     |
| version: 1.3.6                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-08-31T10:27:59Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
- BuildURL: https://www.bitrise.io/build/715d672c0bd67ab9
- APIToken: oCnJV75rw7bYgz7zyDyUWw
- IsCompress: false
- DeployPath: /bitrise/src/app/build/reports/
- NotifyUserGroups: everyone
- NotifyEmailList: 
- IsPublicPageEnabled: true
Issue with input: DeployPath - path not exist at: /bitrise/src/app/build/reports/
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Deploy test reports to Bitrise.io (exit code: 1)              | 4.04 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...://github.com/bitrise-io/steps-deploy-to-bitrise-io/issues |
| Source: https://github.com/bitrise-io/steps-deploy-to-bitrise-io             |
+---+---------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment] 2017-08-31 11:15
Hi @AsifDev21 

```
path not exist at: /bitrise/src/app/build/reports/
```

Means that the path you specified does not exist there. Note: `/bitrise/src` is the directory where your repo is cloned.

**Comment by viktorbenei** [comment] 2017-08-31 11:16
I'll close this here as the issue is most likely not related to the step, but if this would not help @AsifDev21 feel free to contact us at https://discuss.bitrise.io/c/issues/build-issues or through the onsite chat or email on bitrise.io

**Closed by viktorbenei** 2017-08-31 11:16 UTC
