### ISSUE TITLE
Public Install Page for multiple artifacts

### ISSUE THREAD

**Issue by JulioC** [bitrise-io/steps-deploy-to-bitrise-io#43] opened 2017-08-10 05:01 UTC
When building for multiple platforms at the same time, this step will copy all artifacts available and create individual pages for each one, but it will set BITRISE_PUBLIC_INSTALL_PAGE_URL for just one of the generated artifacts.

I believe this should be changed to set a BITRISE_PUBLIC_INSTALL_PAGE_URLS (plural) with a comma separated list of the generated pages or make the install page support multiple platforms at once (which is the best option, but it implies changes in the bitrise platform...).

If you agree with the first option, I'd volunteer to try implement it.

**Comment by viktorbenei** [comment] 2017-08-10 11:25
It's a semi-duplicate of: https://github.com/bitrise-io/steps-deploy-to-bitrise-io/issues/22

@JulioC In any case, if you have the time feel free to go ahead and export all urls, but please follow our guidelines from here: https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md#output-naming-convention

- postfix with `_LIST`
- separate values with pipe (`|`) char. Feel free to add spaces, e.g. `first.url | second.url`

Would be awesome to have it in this step ;)

**Closed** 2017-12-14 12:39 UTC
