### ISSUE TITLE
Will not deploy file if it has space in the name

### ISSUE THREAD

**Issue by charlesbedrosian** [bitrise-io/steps-deploy-to-bitrise-io#46] opened 2017-09-08 06:34 UTC

**Comment by doomsayer13** [comment] 2017-09-08 08:35
Hi @charlesbedrosian,
Thanks for reporting, we'll definitely find a solution for this!

**Comment by trapacska** [comment] 2017-09-25 17:37
Hey @charlesbedrosian! 👋

Just checked the step multiple ways, and looks like it is working as intended. Please see the results below. Could you please provide more info about the build you had this issue?

Thanks!

```
+------------------------------------------------------------------------------+

| (1) deploy-to-bitrise-io@1.3.7                                               |
+------------------------------------------------------------------------------+
| id: deploy-to-bitrise-io                                                     |
| version: 1.3.7                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-09-25T10:25:53-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
- BuildURL: https://www.bitrise.io/build/643ae0386df50b2a
- APIToken: _nwxh5Vd92Yk0HXTYdyPkg
- IsCompress: false
- DeployPath: /Users/vagrant/deploy
- NotifyUserGroups: everyone
- NotifyEmailList: 
- IsPublicPageEnabled: true
Deploying the content of the Deploy directory separately
List of files to deploy
- /Users/vagrant/deploy/filewith spaceinthename.txt
Deploying files
Uploading file: /Users/vagrant/deploy/filewith spaceinthename.txt
creating artifact
  file size: 8B
uploading artifact
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     8    0     0  100     8      0     49 --:--:-- --:--:-- --:--:--    49
finishing artifact
is_enable_public_page is set, but public download isn't allowed for this type of file
Success
You can find the Artifact on Bitrise, on the Build's page: https://www.bitrise.io/build/643ae0386df50b2a
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | deploy-to-bitrise-io@1.3.7                                    | 7.77 sec |
+---+---------------------------------------------------------------+----------+

```

<img width="1436" alt="screen shot 2017-09-25 at 7 26 28 pm" src="https://user-images.githubusercontent.com/1564933/30822186-3e52ef8a-a228-11e7-835b-534e24a0a3bc.png">

**Comment by trapacska** [comment] 2017-10-02 09:44
I am closing the issue now, as it still seems to be working fine.

Please feel free to re-open if you encounter any issues!

**Closed by trapacska** 2017-10-02 09:44 UTC
